const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),esbuild=require('esbuild');
const {chromium}=require(process.env.BETTERNOTE_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BETTERNOTE_QA_TEMP;if(!base||!path.isAbsolute(base))throw Error('Isolated QA root required');
const entry=String.raw`
import React from 'react';import{createRoot}from'react-dom/client';import{App}from'./src/App.jsx';import * as db from'./src/services/db.js';import{autoBackupService as backup}from'./src/services/autoBackupService.js';import{setAppLanguage}from'./src/services/i18n.js';
window.qa={db,backup,alerts:[],calls:[],count:0};setAppLanguage('en');window.alert=m=>qa.alerts.push(m);window.confirm=()=>true;
backup.startScheduledSync=()=>{};
window.electronAPI={isElectron:true,saveBackup:async command=>{if(qa.holdBackup&&command.action==='begin'){qa.backupStarts=(qa.backupStarts||0)+1;await new Promise(resolve=>qa.releaseBackup=resolve);return{success:false,reason:'invalid-backup-data'};}return{success:true,targets:[]};},getDriveSyncCapabilities:async()=>({protocol:1}),scanBackupFolder:async()=>({success:false,reason:qa.restoreError||'invalid-backup-data'}),
exportPdfDocument:async c=>{qa.calls.push(c.action);if(c.action==='capabilities')return{protocol:2,batchPages:2,batchBytes:1000000};if(c.action==='begin'){qa.count=0;return{id:'synthetic-pdf'};}if(c.action==='append'){await new Promise(resolve=>qa.releasePrint=resolve);if(qa.failPrint)return{error:'pdf-print-failed'};qa.count+=c.pages;return{pages:qa.count};}if(c.action==='finish'){await new Promise(resolve=>qa.releaseMerge=resolve);return{pages:qa.count,bytes:new Uint8Array([37,80,68,70,45,49,46,55]).buffer};}return{};},
onCloseSaveRequest:()=>()=>{},onCloseSaveCancelled:()=>()=>{},setLocalSaveGuardReady:()=>{},completeCloseSaveRequest:()=>{}};
qa.seed=async()=>{await db.saveSetting('initialDataSeeded',true);await db.saveSetting('gdrive_backup_method','desktop');await db.saveSetting('gdrive_backup_path','Q:/Synthetic Drive/BetterNote');await db.saveNotebook({id:'progress-note',name:'Surface progress QA',pageCount:4,templateId:'blank'});for(let i=0;i<4;i++)await db.savePage({id:'progress-page-'+i,notebookId:'progress-note',pageIndex:i,templateId:'blank',pageWidth:400,pageHeight:600,strokes:[],textElements:[],imageElements:[]});};
qa.mount=()=>createRoot(document.getElementById('root')).render(<App/>);
`;
(async()=>{const fixture=fs.mkdtempSync(path.join(base,'surface-library-')),passed=[],errors=[];
 const bundle=await esbuild.build({stdin:{contents:entry,resolveDir:root,loader:'jsx'},bundle:true,write:false,format:'iife',platform:'browser',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'qa-workers',setup(build){require('./helpers/recovery-worker.cjs').setupRecoveryWorker(build);build.onResolve({filter:/notebookCover\.worker\.js\?worker&inline$/},()=>({path:'cover',namespace:'qa-cover'}));build.onLoad({filter:/.*/,namespace:'qa-cover'},()=>{const assets=path.join(root,'dist/assets'),file=fs.readdirSync(assets).find(n=>/^notebookCover\.worker-.*\.js$/.test(n));return{contents:fs.readFileSync(path.join(assets,file),'utf8'),loader:'js'};});}}],logLevel:'silent'});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BETTERNOTE_QA_BROWSER,env:{...process.env,TEMP:base,TMP:base}});
 try{const context=await browser.newContext({viewport:{width:1360,height:900},hasTouch:true,acceptDownloads:true});const page=await context.newPage();await page.route('**/*',r=>r.request().url()==='https://surface-ui.invalid/'?r.fulfill({status:200,contentType:'text/html',body:'<div id="root"></div><style>'+fs.readFileSync(path.join(root,'src/index.css'),'utf8')+'</style>'}):r.abort());
 page.on('pageerror',e=>errors.push(e.message));await page.goto('https://surface-ui.invalid/');await page.addScriptTag({content:bundle.outputFiles[0].text});await page.evaluate(async()=>{await qa.seed();qa.mount();});await page.getByText('Surface progress QA',{exact:true}).first().waitFor();
 const check=async(name,fn)=>{await fn();passed.push(name);console.log('PASS '+name);};const exportMenu=async()=>{await page.locator('.bn-gn-chevron-btn').click();await page.getByText('Export to PDF',{exact:true}).click();};
 await check('Library context export reports real print/merge progress under the notebook name and prevents duplicate jobs',async()=>{
 await exportMenu();await page.waitForFunction(()=>qa.releasePrint);const p=page.locator('.bn-library-export-progress');await p.waitFor();assert.equal(await p.getAttribute('data-export-stage'),'print');assert.ok(Number(await p.locator('progress').getAttribute('value'))<1);
 await page.locator('.bn-gn-chevron-btn').click();assert.equal(await page.getByText('Export to PDF',{exact:true}).locator('..').isDisabled(),true);await page.locator('.bn-gn-chevron-btn').click();assert.equal(await page.evaluate(()=>qa.calls.filter(c=>c==='begin').length),1);
 await page.evaluate(()=>{qa.releasePrint();qa.releasePrint=null;});await page.waitForFunction(()=>qa.releasePrint);await page.evaluate(()=>qa.releasePrint());await page.waitForFunction(()=>qa.releaseMerge);
 assert.equal(await p.getAttribute('data-export-stage'),'merge');assert.ok(Number(await p.locator('progress').getAttribute('value'))<1);await page.screenshot({path:path.join(fixture,'export-progress.png')});const downloaded=page.waitForEvent('download');await page.evaluate(()=>qa.releaseMerge());await downloaded;await page.waitForFunction(()=>document.querySelector('[data-export-stage="done"]'));assert.equal(await p.locator('progress').getAttribute('value'),'1');assert.deepEqual(await page.evaluate(()=>qa.alerts),[]);
 });
 await check('Successful Library export removes its completed progress after three seconds',async()=>{await page.locator('.bn-library-export-progress').waitFor({state:'hidden',timeout:5000});});
 await check('Failed Library export clears its busy state and can retry immediately',async()=>{await page.evaluate(()=>{qa.failPrint=true;qa.releasePrint=null;});await exportMenu();await page.waitForFunction(()=>qa.releasePrint);await page.evaluate(()=>qa.releasePrint());await page.waitForFunction(()=>document.querySelector('[data-export-stage="error"]'));await page.locator('.bn-gn-chevron-btn').click();assert.equal(await page.getByText('Export to PDF',{exact:true}).locator('..').isDisabled(),false);await page.locator('.bn-gn-chevron-btn').click();});
 await check('Restore opened from the top bar remains visible with its folder after repeated read failures',async()=>{
 await page.locator('.bn-document-tab-bar .bn-backup-indicator').click();await page.locator('.bn-backup-dialog').waitFor();await page.getByRole('tab',{name:'Google Drive',exact:true}).click();const restore=page.getByRole('button',{name:'Restore from Folder',exact:true});await restore.waitFor();
 for(const error of ['invalid-backup-data','backup-incomplete','backup-read-timeout']){await page.evaluate(error=>qa.restoreError=error,error);await restore.click();await page.waitForFunction(()=>!document.querySelector('.bn-backup-recovery-overlay'));await page.waitForTimeout(150);assert.equal(await restore.isVisible(),true);assert.equal(await restore.isEnabled(),true);assert.equal(await page.locator('[data-drive-folder-path]').innerText(),'Q:/Synthetic Drive/BetterNote');}await page.screenshot({path:path.join(fixture,'restore-retry.png')});
 });
 await check('Drive has one Backup button; a pen tap starts one job and shows its busy state immediately',async()=>{
 const button=page.locator('.bn-backup-btn-sync-now');assert.equal(await button.count(),1);assert.equal(await page.getByRole('button',{name:'Prepare files for Drive',exact:true}).count(),0);
 await page.evaluate(()=>qa.holdBackup=true);const cdp=await page.context().newCDPSession(page),rect=await button.boundingBox(),x=rect.x+rect.width/2,y=rect.y+rect.height/2;
 const tap=async()=>{await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',buttons:1,clickCount:1,pointerType:'pen',force:.5});await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',buttons:0,clickCount:1,pointerType:'pen',force:0});};
 await tap();await page.waitForFunction(()=>qa.releaseBackup);assert.equal(await button.isDisabled(),true);await tap();await tap();assert.equal(await page.evaluate(()=>qa.backupStarts),1);
 await page.evaluate(()=>qa.releaseBackup());await button.waitFor();await page.waitForFunction(()=>!document.querySelector('.bn-backup-btn-sync-now').disabled);await page.evaluate(()=>qa.backup.stopScheduledSync());
 });
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:passed.length,failed:0,fixture,errors,syntheticOnly:true}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
