const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs').promises,path=require('node:path');
const {createBackupReader}=require('../electron/backupReader.cjs');
const {createBackupSyncReader}=require('../electron/backupSyncReader.cjs');
const {createBackupWriter}=require('../electron/backupWriter.cjs');
const qa=process.env.BETTERNOTE_QA_TEMP;if(!qa||!path.isAbsolute(qa))throw Error('Isolated QA folder required');
const summary={lastSync:10,backupTarget:'drive',activeNotebooksCount:1,savedCount:1};
const note={id:'legacy-note',name:'Legacy writing',pageCount:1,updatedAt:10,pages:[{id:'legacy-page',notebookId:'legacy-note',pageIndex:0,strokes:[{id:'ink',points:[{x:1,y:2},{x:30,y:40}]}],textElements:[],imageElements:[]}]};
async function fixture(){const root=await fs.mkdtemp(path.join(qa,'surface-legacy-'));await fs.mkdir(path.join(root,'Full_System'));await fs.mkdir(path.join(root,'Editable_Notes'));await fs.writeFile(path.join(root,'Full_System/backup_manifest.json'),JSON.stringify(summary));await fs.writeFile(path.join(root,'Full_System/BetterNote_Latest_Backup.json'),JSON.stringify({version:1,appName:'BetterNote',notebooks:[note],folders:[]}));await fs.writeFile(path.join(root,'Editable_Notes/Notebook-old-name.bnote'),JSON.stringify(note));return root;}
async function upgrade(root,proof,hook){const local=await fs.mkdtemp(path.join(qa,'surface-local-'));const writer=createBackupWriter({localDir:local,beforeReplace:hook});const metadata={folders:[],notebooks:[{...note,pages:undefined}]};const {backupMetadataRevision}=await import('../src/utils/backupRevision.js');const revision=backupMetadataRevision(metadata);const options={driveBackupPath:root,driveSyncGuard:{ready:true,manifestHash:proof.manifestHash,legacyUpgrade:proof,deviceId:'surface-fixture'}};const begin=await writer.execute({action:'begin',jobId:'upgrade',metadata,metadataRevision:revision,phase:'data',...options});const written=await writer.execute({action:'notebook',jobId:'upgrade',notebook:note});const finish=await writer.execute({action:'finish',jobId:'upgrade',metadataRevision:revision});return {begin,written,finish};}
test('Old summary manifests restore intact and upgrade to guarded v2 without removing original notebooks',async()=>{const root=await fixture(),reader=createBackupReader();const legacy=await reader.execute({folderPath:root});assert.equal(legacy.success,true,legacy.reason);assert.deepEqual(legacy.data.notebooks,[note]);assert.equal(legacy.legacyUpgrade.files.length,2);const original=await fs.readFile(path.join(root,'Editable_Notes/Notebook-old-name.bnote'));const result=await upgrade(root,legacy.legacyUpgrade);assert.equal(result.finish.targets.find(t=>t.kind==='drive').dataSuccess,true,JSON.stringify(result.finish));assert.deepEqual(await fs.readFile(path.join(root,'Editable_Notes/Notebook-old-name.bnote')),original);const current=await reader.execute({folderPath:root});assert.equal(current.success,true,current.reason);assert.deepEqual(current.data.notebooks,[note]);const remote=await createBackupSyncReader().execute({folderPath:root,syncMode:'preview'});assert.equal(remote.success,true,remote.reason);assert.equal(remote.notes.length,1);const histories=await fs.readdir(path.join(root,'Backup_History/Manifests'));assert.ok(histories.length>=1);});
test('Unknown manifest versions still block recovery',async()=>{const root=await fixture();await fs.writeFile(path.join(root,'Full_System/backup_manifest.json'),JSON.stringify({...summary,version:99}));assert.equal((await createBackupReader().execute({folderPath:root})).reason,'invalid-backup-manifest');});
test('A damaged old notebook never imports or authorizes upgrade',async()=>{const root=await fixture();await fs.writeFile(path.join(root,'Editable_Notes/Notebook-old-name.bnote'),'{');const result=await createBackupReader().execute({folderPath:root});assert.equal(result.success,false);assert.equal(result.data,undefined);assert.equal(result.legacyUpgrade,undefined);});
test('A legacy notebook changed after validation blocks Drive writes and keeps incoming bytes',async()=>{const root=await fixture();const scanned=await createBackupReader().execute({folderPath:root});const file=path.join(root,'Editable_Notes/Notebook-old-name.bnote'),incoming=JSON.stringify({...note,updatedAt:20});await fs.writeFile(file,incoming);const result=await upgrade(root,scanned.legacyUpgrade);assert.equal(result.begin.targets.find(t=>t.kind==='drive').error,'backup-changed-externally');assert.equal(await fs.readFile(file,'utf8'),incoming);assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'Full_System/backup_manifest.json'))),summary);});
test('An old folder changed during migration aborts before replacing its full snapshot',async()=>{const root=await fixture();const scanned=await createBackupReader().execute({folderPath:root});const full=path.join(root,'Full_System/BetterNote_Latest_Backup.json'),before=await fs.readFile(full);let changed=false;const result=await upgrade(root,scanned.legacyUpgrade,async({relative})=>{if(!changed&&relative.endsWith('.bnote')){changed=true;await fs.appendFile(path.join(root,'Editable_Notes/Notebook-old-name.bnote'),' ');}});assert.equal(changed,true);assert.equal(result.written.targets.find(t=>t.kind==='drive').error,'backup-changed-externally');assert.deepEqual(await fs.readFile(full),before);});
