// Isolated browser checks: guide navigation must not mutate notebooks or folders.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),esbuild=require('esbuild');
const {chromium}=require(process.env.BETTERNOTE_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BETTERNOTE_QA_TEMP;
if(!base||!path.isAbsolute(base))throw Error('An isolated QA directory is required');
const entry=`import React from 'react';import{createRoot}from'react-dom/client';import{App}from'./src/App.jsx';import * as db from'./src/services/db.js';import{autoBackupService as backup}from'./src/services/autoBackupService.js';import{setAppLanguage}from'./src/services/i18n.js';import{lessons,categories,searchLessons}from'./src/components/Guide/guideContent.js';import{figures}from'./src/components/Guide/guideFigures.js';window.qa={db,backup,lessons,categories,figures,searchLessons};setAppLanguage('th');backup.startScheduledSync=()=>{};window.electronAPI={onCloseRequested:()=>()=>{},getAppInfo:async()=>({version:'1.3.0',distribution:'installer'}),saveBackup:async()=>({success:true,targets:[]}),scanBackupFolder:async()=>({success:false,reason:'not-found'})};window.alert=()=>{};qa.mount=()=>createRoot(document.getElementById('root')).render(<App/>);`;
(async()=>{
 const dir=fs.mkdtempSync(path.join(base,'user-guide-')),errors=[],failedRequests=[],passed=[];
 const bundle=await esbuild.build({stdin:{contents:entry,resolveDir:root,loader:'jsx'},bundle:true,write:false,format:'iife',platform:'browser',loader:{'.css':'empty'},define:{'process.env.NODE_ENV':'"production"','import.meta.env.BASE_URL':'"./"'},plugins:[{name:'qa-workers',setup:require('./helpers/recovery-worker.cjs').setupRecoveryWorker}],logLevel:'silent'});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BETTERNOTE_QA_BROWSER});
 try{
 const context=await browser.newContext({viewport:{width:1368,height:912},hasTouch:true});const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!=='https://guide-test.invalid')return route.abort();const n=decodeURIComponent(u.pathname.slice(1));if(!n)return route.fulfill({contentType:'text/html',body:'<!doctype html><link rel="stylesheet" href="/fonts/fonts.css"><link rel="stylesheet" href="/qa.css"><div id="root"></div>'});if(n==='qa.css')return route.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(root,'src/index.css'),'utf8')+'\n'+fs.readFileSync(path.join(root,'src/components/Guide/UserGuide.css'),'utf8')});const target=path.resolve(root,'public',n);if(target.startsWith(path.join(root,'public')+path.sep)&&fs.existsSync(target))return route.fulfill({path:target});failedRequests.push(n);return route.fulfill({status:404,body:''});});
 await page.goto('https://guide-test.invalid/');await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.evaluate(async()=>{const now=Date.now();await qa.db.saveSetting('initialDataSeeded',true);await qa.db.saveFolder({id:'guide-test-folder',name:'Guide QA course',parentId:null,updatedAt:now,createdAt:now});await qa.db.saveNotebook({id:'guide-test-note',name:'Guide QA notebook',folderId:'guide-test-folder',pageCount:1,templateId:'blank',updatedAt:now,createdAt:now});await qa.db.savePage({id:'guide-test-page',notebookId:'guide-test-note',pageIndex:0,strokes:[],textElements:[{id:'t',text:'Preserve this writing',x:80,y:80}],imageElements:[],updatedAt:now});qa.mount();});
 await page.locator('.bn-gn-folder-name').waitFor();
 const snapshot=()=>page.evaluate(async()=>{const db=await qa.db.openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(['folders','notebooks','pages'],'readonly'),data={};for(const name of ['folders','notebooks','pages']){const r=tx.objectStore(name).getAll();r.onsuccess=()=>data[name]=r.result;}tx.oncomplete=()=>resolve(JSON.stringify(data));tx.onerror=reject;});});
 const before=await snapshot(),guide=()=>page.locator('.bn-sidebar-item').filter({hasText:'คู่มือการใช้งาน'}),main=page.locator('.bn-guide');
 const check=async(name,fn)=>{await fn();passed.push(name);console.log('PASS '+name);};
 await check('Guide entry follows Favorites and returning preserves the open folder',async()=>{
 const items=await page.locator('.bn-sidebar-item').evaluateAll(es=>es.map(e=>e.textContent));assert.ok(items.findIndex(t=>t.includes('คู่มือการใช้งาน'))===items.findIndex(t=>t.includes('รายการโปรด'))+1);
 await page.locator('.bn-gn-folder-graphic-wrapper').click();await page.locator('.bn-gn-book-name').filter({hasText:'Guide QA notebook'}).waitFor();await guide().click();await main.waitFor();await page.locator('.bn-sidebar-item').filter({hasText:'เอกสาร'}).click();await page.locator('.bn-gn-book-name').filter({hasText:'Guide QA notebook'}).waitFor();await guide().click();
 });
 await check('Every lesson has readable bilingual instructions, valid related links and annotated real images',async()=>{
 const result=await page.evaluate(async()=>{const bad=[];for(const l of qa.lessons){for(const lang of ['th','en'])if(!l.title[lang]||!l.intro[lang]||!l.steps[lang]?.length)bad.push(l.id+lang);if(!qa.figures[l.figure])bad.push(l.id+' figure');for(const id of l.related)if(!qa.lessons.some(x=>x.id===id))bad.push(l.id+' link '+id);}for(const [id,f]of Object.entries(qa.figures)){const image=new Image();image.src='./user-guide/'+f.file;await image.decode();if(image.naturalWidth!==f.width||image.naturalHeight!==f.height||!f.marks.length)bad.push(id+' image');for(const m of f.marks)if(m.x<0||m.y<0||m.x+m.w>f.width+2||m.y+m.h>f.height+2)bad.push(id+' bounds');}return{bad,count:qa.lessons.length,categories:qa.categories.length};});assert.deepEqual(result.bad,[]);assert.equal(result.categories,10);assert.ok(result.count>=55);
 });
 await check('Search supports Thai and English, no results and category navigation',async()=>{
 const search=main.locator('input[type=search]');await search.fill('Restore');await main.locator('.bn-guide-lesson-list button').first().waitFor();assert.ok(await main.locator('.bn-guide-lesson-list button').count()>2);await search.fill('คำที่ไม่มีผลลัพธ์xxxxx');await main.locator('.bn-guide-empty').waitFor();await main.locator('.bn-guide-empty button').click();await main.locator('.bn-guide-category-grid').waitFor();await main.locator('.bn-guide-category-grid button').filter({hasText:'บันทึก สำรอง และกู้คืน'}).click();assert.ok(await main.locator('.bn-guide-lesson-list button').count()>=12);
 });
 await check('The language selector changes lesson text and controls together',async()=>{
 await main.locator('select').selectOption('en');assert.equal(await main.locator('h1').innerText(),'Save, back up & restore');await main.locator('.bn-guide-lesson-list button').filter({hasText:'Restore large notebooks'}).click();assert.equal(await main.locator('h1').innerText(),'Restore large notebooks and cancel safely');await main.locator('select').selectOption('th');assert.equal(await main.locator('h1').innerText(),'กู้สมุดใหญ่และยกเลิกก่อนนำเข้า');await main.locator('.bn-guide-breadcrumb button').last().click();
 });
 await check('Article images enlarge, Escape closes and keyboard focus returns',async()=>{
 await main.locator('.bn-guide-lesson-list button').filter({hasText:'ดูไฟล์'}).first().click();await main.locator('.bn-guide-article').waitFor();const expand=main.locator('.bn-guide-figure-top button').first();await expand.focus();await expand.click();await page.locator('dialog[open]').waitFor();await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.equal(await expand.evaluate(e=>document.activeElement===e),true);await main.locator('.bn-guide-brand').click();
 });
 await check('Surface layouts and both themes have no guide horizontal overflow',async()=>{
 for(const width of [1368,1024,800]){await page.setViewportSize({width,height:912});for(const theme of ['dark','light']){await page.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await page.waitForTimeout(80);assert.equal(await main.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);assert.equal(await main.locator('.bn-guide-scroll').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);await page.screenshot({path:path.join(dir,'home-'+width+'-'+theme+'.png')});} }
 await page.setViewportSize({width:1024,height:912});await main.locator('.bn-guide-toc-toggle').click();await main.locator('.bn-guide-toc').getByRole('button',{name:'เขียนและไฮไลท์',exact:true}).click();await main.locator('.bn-guide-lesson-list button').first().click();await page.screenshot({path:path.join(dir,'article-surface.png')});
 });
 await check('Reading the manual never changes notebook, page or folder data',async()=>assert.equal(await snapshot(),before));
 await check('Leaving the guide for Favorites keeps normal library navigation',async()=>{await page.locator('.bn-sidebar-item').filter({hasText:'รายการโปรด'}).click();await page.locator('.bn-sidebar-item').filter({hasText:'เอกสาร'}).click();await page.locator('.bn-gn-folder-name').filter({hasText:'Guide QA course'}).waitFor();});
 assert.deepEqual(errors,[]);assert.deepEqual(failedRequests,[]);console.log(JSON.stringify({passed:passed.length,failed:0,screenshots:dir}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
